# Generated by Django 4.2.5 on 2024-07-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_kyc_identity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in-active', 'Inactive')], default='in-active', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_licence', "Driver's License"), ('international_passport', 'International Passport')], max_length=140),
        ),
    ]
