# Generated by Django 4.2.5 on 2024-07-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport')], max_length=140),
        ),
    ]
