# Generated by Django 4.2.5 on 2024-07-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_uid',
            new_name='transaction_id',
        ),
    ]
