# Generated by Django 4.2.5 on 2024-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
