# Generated by Django 4.2.5 on 2024-07-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_creditcard_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='number',
            new_name='card_number',
        ),
    ]
