# Generated by Django 4.2.5 on 2024-08-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_creditcard_card_number_alter_creditcard_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='year',
            field=models.IntegerField(),
        ),
    ]
